apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  name: codespace-microservice
  input:
    manifests:
      - deploy.yaml
  pipeline:
    stages:
      - name: K8S_CANARY_ROLLOUT
        with:
          replicas: 1
      - name: WAIT_APPROVAL
      - name: K8S_PRIMARY_ROLLOUT
      - name: K8S_CANARY_CLEAN